---
type: chart
envValues:
  - envVar: CLUSTER_API
    value: "http://cluster-manager-api-cluster-manager-api"
  - envVar: K8S_VERSION
    value: "1.12.6"
  - envVar: CMA_CALLBACK_URL
    value: "https://example.cnct.io"
  - envVar: KEY_HOME
    value: "/var/tmp/ims-kaas/.ssh"
  - envVar: CMA_CALLBACK_REQUESTID
    value: "12345"
  - envVar: AKS_K8S_VERSION
    value: "1.12.6"
  - envVar: AZURE_CLIENT_ID
    secret: jobs/ims-kaas/AZURE_CLIENT_ID
  - envVar: AZURE_CLIENT_SECRET
    secret: jobs/ims-kaas/AZURE_CLIENT_SECRET
  - envVar: AZURE_TENANT_ID
    secret: jobs/ims-kaas/AZURE_TENANT_ID
  - envVar: DEBUG
    value: "0"
builds:
  - image: samsung_cnct/ims-kaas
    context: ims-kaas
    chart: ims-kaas
    tagValue: images.operator.tag
    dockerContext: .
  - image: samsung_cnct/ims-kaas-test-scripts
    context: ims-kaas-test-scripts
    dockerContext: .
deployments:
  - chart: ims-kaas
    timeout: 600
    retries: 2
    setAppVersion: true
    release: ims-kaas
prod:
  doDeploy: none
