apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: machines.cluster.sds.samsung.com
spec:
  group: cluster.sds.samsung.com
  names:
    kind: Machine
    plural: machines
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            clustername:
              type: string
            roles:
              items:
                type: string
              type: array
            sshconfig:
              properties:
                host:
                  type: string
                port:
                  format: int32
                  type: integer
                secret:
                  type: string
                username:
                  type: string
              type: object
            taints:
              items:
                type: object
              type: array
          type: object
        status:
          properties:
            kubernetesVersion:
              type: string
            lastUpdated:
              format: date-time
              type: string
            phase:
              type: string
          required:
          - kubernetesVersion
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
