apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: machines.cluster.sds.samsung.com
spec:
  group: cluster.sds.samsung.com
  names:
    kind: Machine
    plural: machines
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            configSource:
              type: object
            metadata:
              type: object
            providerSpec:
              properties:
                value:
                  type: object
                valueFrom:
                  properties:
                    machineClass:
                      properties:
                        provider:
                          type: string
                      type: object
                  type: object
              type: object
            taints:
              items:
                type: object
              type: array
            versions:
              properties:
                controlPlane:
                  type: string
                kubelet:
                  type: string
              required:
              - kubelet
              type: object
          required:
          - providerSpec
          type: object
        status:
          properties:
            addresses:
              items:
                type: object
              type: array
            conditions:
              items:
                type: object
              type: array
            errorMessage:
              type: string
            errorReason:
              type: string
            lastUpdated:
              format: date-time
              type: string
            nodeRef:
              type: object
            providerStatus:
              type: object
            versions:
              properties:
                controlPlane:
                  type: string
                kubelet:
                  type: string
              required:
              - kubelet
              type: object
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
