apiVersion: cluster.sds.samsung.com/v1alpha1
kind: Machine
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: new-worker
spec:
  # Add fields here
  clusterref: cluster
  roles:
    - worker
  labels:
    role: worker
  sshconfig:
    publichost: 168.61.21.247
    host: 10.240.0.10
    port: 22
    username: root
    secret: ssh-key