replicaCount: 1
images:
   operator:
      repository: quay.io/samsung_cnct/cma-ssh
      tag: 0.1.0
      pullPolicy: Always
   bootstrap:
      repository: quay.io/samsung_cnct/cma-ssh-bootstrap
      tag: 0.1.0
      pullPolicy: Always

# installation settings
install:
   operator: true
   operatorIngress: false
   crds: true
   bootstrap: true
   bootstrapIp: '192.168.64.24'
   airgapProxyIp: '182.195.81.113'

service:
   operator:
      port: 80
      targetPort: 9020
      type: NodePort
      nodePort: 30006
   bootstrap:
      port: 80
      nodePort: 30005

ingress:
   grpc:
      host: cma-ssh-grpc.ontario.cluster.cnct.io
   rest:
      host: cma-ssh.ontario.cluster.cnct.io

# short resource name override
nameOverride: ''

# long resource name override
fullnameOverride: ''

# keep CRDs installed after a release deletion
keepCRDs: false

# install RBAC resources
rbac: true

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
