{{- if .Values.install.operator }}
{{- if .Values.install.operatorIngress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    annotations:
        nginx.ingress.kubernetes.io/grpc-backend: "true"
    name: {{ include "cma-ssh.name" . }}-grpc
spec:
    rules:
        - host: {{ .Values.ingress.grpc.host }}
          http:
              paths:
                  - backend:
                        serviceName: {{ include "cma-ssh.name" . }}
                        servicePort: {{ .Values.service.operator.port | int }}
                    path: /
    tls:
        - hosts:
              - {{ .Values.ingress.grpc.host }}
          secretName: {{ include "cma-ssh.name" . }}-tls
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: {{ include "cma-ssh.name" . }}
spec:
    rules:
        - host: {{ .Values.ingress.rest.host }}
          http:
              paths:
                  - backend:
                        serviceName: {{ include "cma-ssh.name" . }}
                        servicePort: {{ .Values.service.operator.port | int }}
                    path: /
    tls:
        - hosts:
              - {{ .Values.ingress.rest.host }}
          secretName: {{ include "cma-ssh.name" . }}-tls
{{- end }}
{{- end }}