{{- if .Values.rbac }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cma-ssh.name" . }}
  labels:
    helm.sh/chart: {{ include "cma-ssh.chart" . }}
    app.kubernetes.io/name: {{ include "cma-ssh.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" | trunc 63 }}
{{- end }}