apiVersion: cluster.sds.samsung.com/v1alpha1
kind: Cluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: cluster-sample
spec:
  # Add fields here
  clusterNetwork:
    pods:
    serviceDomain:
    services:

  kubernetesVersion: 1.10.6
