apiVersion: cluster.cnct.sds.samsung.com/v1alpha1
kind: CnctMachine
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: master
spec:
  # Add fields here
  clusterref: cluster
  roles:
    - etcd
    - master
  labels:
    role: controlPlane
  sshconfig:
    publichost: 13.64.100.33
    host: 10.240.0.8
    port: 22
    username: root
    secret: ssh-key
---
apiVersion: cluster.cnct.sds.samsung.com/v1alpha1
kind: CnctMachine
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: worker
spec:
  # Add fields here
  clusterref: cluster
  roles:
  - worker
  labels:
    role: worker
  sshconfig:
    publichost: 40.78.16.250
    host: 10.240.0.9
    port: 22
    username: root
    secret: ssh-key
