apiVersion: cluster.cnct.sds.samsung.com/v1alpha1
kind: CnctMachine
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: master
spec:
  # Add fields here
  clusterref: cluster
  roles:
    - etcd
    - master
  labels:
    role: controlPlane
  instanceType: master
---
apiVersion: cluster.cnct.sds.samsung.com/v1alpha1
kind: CnctMachine
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: worker
spec:
  # Add fields here
  clusterref: cluster
  roles:
  - worker
  labels:
    role: worker
  instanceType: standard
