apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: '{{.Release.Name}}'
    app.kubernetes.io/managed-by: '{{.Release.Service}}'
    app.kubernetes.io/name: '{{include "cma-ssh.name" .}}'
    app.kubernetes.io/version: '{{.Chart.AppVersion | replace "+" "_" | trunc 63}}'
    controller-tools.k8s.io: "1.0"
    helm.sh/chart: '{{include "cma-ssh.chart" .}}'
  name: appbundles.addons.cnct.sds.samsung.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    description: appbundle status
    name: Status
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: addons.cnct.sds.samsung.com
  names:
    kind: AppBundle
    plural: appbundles
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            command:
              description: 'Command run in image (ex: helm install stable/nginx-ingress)'
              type: string
            image:
              description: Image used for install (including tag)
              type: string
          required:
          - image
          type: object
        status:
          properties:
            phase:
              description: AppBundle status
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
